sudo: required

services:
  - docker

env:
  matrix:
    - TAG='osc3.0.0'
    - TAG='osc3.0.1'
    - TAG='osc3.1.0'
    - TAG='osc3.2.0'
    - TAG='osc3.2.1'
    - TAG='osc3.3.0'
    - TAG='osc3.4.0'
    - TAG='osc3.4.1'
    - TAG='osc3.5.0'
    - TAG='osc3.6.0'
    - TAG='osc3.7.0'
    - TAG='osc3.8.0'
    - TAG='osc3.8.1'
    - TAG='osc3.8.2'
    - TAG='osc3.9.0'
    - TAG='osc3.10.0'
    - TAG='osc3.11.0'
    - TAG='osc3.12.0'
    - TAG='osc3.12.1'
    - TAG='osc3.13.0'
    - TAG='osc3.14.0'
    - TAG='osc3.14.1'
    - TAG='osc3.14.2'
    - TAG='osc3.15.0'
    - TAG='osc3.16.0'

script:
  - docker build -t lwieske/openstackclient:$TAG $TAG
